server:
  port: 8004
  error:
    include-message: always
    include-binding-errors: always


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todo
    username: postgres
    password: password
  session:
    store-type: redis
  redis:
    host: 127.0.0.1
    port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect

